### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by SaymonDzen** [jakubjastrabik/smartctl_ssacli_exporter#1]
go version
go version go1.15 linux/amd64

~/smartctl_ssacli_exporter# go get 
cannot find package "github.com/prometheus/common/log" in any of:
        /usr/local/go/src/github.com/prometheus/common/log (from $GOROOT)
        /root/work/src/github.com/prometheus/common/log (from $GOPATH)

**Comment by jakubjastrabik** [comment]
Hi, I tried to build on GO version 1.16 and works fine for me. So you can try to update your Go to the new version. But I think this issue maybe was because you have the wrong install Go lang (I have some similar kind of issue in past). You can try "go get github.com/prometheus/common" and download the package manually. Or just download compiled binary files from releases. https://github.com/jakubjastrabik/smartctl_ssacli_exporter/releases

Please let me know if you solved this issue or not :)

**Comment by SaymonDzen** [comment]
from release file very longtime response
curl -o /dev/null -s -w 'Establish Connection: %{time_connect}s\nTTFB: %{time_starttransfer}s\nTotal: %{time_total}s\n'  http://127.0.0.1:9633/metrics
Establish Connection: 0.000117s
TTFB: 18.628642s
Total: 18.628976s

prometheus server says
Get "http://backup.e:9633/metrics": context deadline exceeded

**Comment by SaymonDzen** [comment]
# ssacli version

   SSACLI Version: 4.17.6.0 2020-01-07
   SOULAPI Version: 4.17.6.0 2020-01-07

OS Debian 10

**Comment by jakubjastrabik** [comment]
Hi, please can you send me a Prometheus config file, for this scraping? The exporter has a long time to retrieve data from SSACLI, so sometimes Prometheus can hit max scrap duration, and then you can get this type of error, but I see this error many times when I wrong config someone on the exporter or Prometheus sides. But I need to see more things, can you send the log file from the exporter too?

**Comment by SaymonDzen** [comment]
```
global:
  scrape_interval: 15s 
  scrape_timeout: 10s
  evaluation_interval: 15s 
  - job_name: 'office'
      static_configs:
      - targets: [
        'backup.e:9100',
        'backup.e:9633'
      ]

    relabel_configs:
      - source_labels: [__address__]
        separator: ':'
        regex: '(.*):(9100|9633|)'
        replacement: '${1}'
        target_label: instance
```
I use the netdata plugin https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin/hpssa and there have been no problems with the interval so far 
```
  - job_name: 'netdata'
    metrics_path: /api/v1/allmetrics
    params:
      format: [prometheus]
    honor_labels: true
    static_configs:
      - targets: ['backup.e:19999']
    relabel_configs:
      - source_labels: [__address__]
        separator: ':'
        regex: '(.*):(19999)'
        replacement: '${1}'
        target_label: instance
```
What log does the exporter write to by default?
